services:
  # 后端应用服务
  backend:
    build: .
    container_name: my-website-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - my-website-network

networks:
  my-website-network:
    driver: bridge