services:
  # 后端应用服务
  backend:
    build: .
    container_name: my-website-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      # 数据库配置
      - DB_TYPE=mysql
      - DB_HOST=123.60.102.168
      - DB_PORT=3306
      - DB_USERNAME=my-website
      - DB_PASSWORD=root123
      - DB_DATABASE=my-website
      # 服务器配置
      - PORT=3000
      # 环境配置
      - NODE_ENV=development
      # 邮件配置
      - MAIL_HOST=smtp.163.com
      - MAIL_PORT=465
      - MAIL_USER=h321991417@163.com
      - MAIL_PASS=GPTajdXjGHtmayQL
      - MAIL_FROM=万汇六 <h321991417@163.com>
    volumes:
      - ./uploads:/app/uploads  # 映射uploads目录，确保图片持久化
    networks:
      - my-website-network
      
  nginx-backend:
    image: nginx:alpine  # 轻量版Nginx镜像
    ports:
      - "3000:443"  # 宿主机3000端口映射到Nginx容器的443（HTTPS）
    volumes:
      # 挂载Nginx配置文件
      - /www/docker/nginx-backend/nginx.conf:/etc/nginx/nginx.conf
      # 挂载SSL证书目录
      - /www/docker/nginx-backend:/etc/nginx/cert
    networks:
      - backend-network  # 加入和后端相同的网络
    depends_on:
      - backend  # 确保后端服务先启动
    restart: always
networks:
  my-website-network:
    driver: bridge