services:
  # 后端应用服务
  backend:
    build: .
    container_name: my-website-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      # 数据库配置
      - DB_TYPE=mysql
      - DB_HOST=123.60.102.168
      - DB_PORT=3306
      - DB_USERNAME=my-website
      - DB_PASSWORD=root123
      - DB_DATABASE=my-website
      # 服务器配置
      - PORT=3000
      # 环境配置
      - NODE_ENV=development
      # 邮件配置
      - MAIL_HOST=smtp.163.com
      - MAIL_PORT=465
      - MAIL_USER=h321991417@163.com
      - MAIL_PASS=GPTajdXjGHtmayQL
      - MAIL_FROM=万汇六 <h321991417@163.com>
    volumes:
      - ./uploads:/app/uploads  # 映射uploads目录，确保图片持久化
    networks:
      - my-website-network

networks:
  my-website-network:
    driver: bridge